"use client";

import { useMemo } from "react";
import Link from "next/link";
import { format } from "date-fns";
import { DataTable, type DataTableColumn } from "@/components/ui-ems/data-table";

export type ReportHistoryRow = {
  id: string;
  timestamp: string;
  kind: string;
  evidenceId: string | null;
  entityId: string;
  caseNumber: string | null;
  filename: string;
  actorName: string;
  actorRole: string;
};

export function ReportsHistoryTable({ rows }: { rows: ReportHistoryRow[] }) {
  const columns = useMemo<DataTableColumn<ReportHistoryRow>[]>(
    () => [
      {
        key: "generated",
        header: "Generated",
        sortable: true,
        sortValue: (r) => new Date(r.timestamp).getTime(),
        cell: (r) => (
          <span className="whitespace-nowrap text-muted-ems">
            {format(new Date(r.timestamp), "dd MMM yyyy HH:mm")}
          </span>
        ),
      },
      {
        key: "kind",
        header: "Kind",
        sortable: true,
        sortValue: (r) => r.kind,
        cell: (r) => (
          <span className="rounded-md border border-accent-reports/30 bg-accent-reports/10 px-2 py-0.5 text-xs font-medium text-accent-reports">
            {r.kind}
          </span>
        ),
      },
      {
        key: "evidence",
        header: "Evidence / case",
        sortable: true,
        sortValue: (r) => r.evidenceId ?? r.caseNumber ?? "",
        cell: (r) => (
          <div>
            {r.evidenceId ? (
              <Link
                href={`/evidence/${r.entityId}?tab=reports`}
                className="font-mono text-sm font-medium text-accent-reports hover:underline"
              >
                {r.evidenceId}
              </Link>
            ) : (
              "—"
            )}
            {r.caseNumber ? (
              <p className="text-muted-ems">Case {r.caseNumber}</p>
            ) : null}
          </div>
        ),
      },
      {
        key: "filename",
        header: "Filename",
        sortable: true,
        sortValue: (r) => r.filename,
        cell: (r) => (
          <span className="font-mono text-xs">{r.filename}</span>
        ),
      },
      {
        key: "actor",
        header: "Generated by",
        sortable: true,
        sortValue: (r) => r.actorName.toLowerCase(),
        cell: (r) => (
          <div>
            {r.actorName}
            <span className="block text-muted-ems">{r.actorRole}</span>
          </div>
        ),
      },
    ],
    []
  );

  return (
    <DataTable
      columns={columns}
      data={rows}
      getRowId={(r) => r.id}
      emptyTitle="No reports generated yet"
      emptyMessage="Open an evidence item’s Reports tab or use bulk case generate to create the first PDF."
      filterPlaceholder="Filter reports…"
      filterFn={(row, q) =>
        (row.evidenceId?.toLowerCase().includes(q) ?? false) ||
        (row.caseNumber?.toLowerCase().includes(q) ?? false) ||
        row.filename.toLowerCase().includes(q) ||
        row.actorName.toLowerCase().includes(q) ||
        row.kind.toLowerCase().includes(q)
      }
    />
  );
}
