import Link from "next/link";
import { redirect } from "next/navigation";
import { format } from "date-fns";
import { BulkCaseReportForm } from "@/components/reports/bulk-case-report-form";
import { EmptyState } from "@/components/ui-ems/empty-state";
import { ModuleBadge } from "@/components/ui-ems/module-badge";
import { PageHeader } from "@/components/ui-ems/page-header";
import { getSession } from "@/lib/auth";
import { can } from "@/lib/rbac";
import { prisma } from "@/lib/prisma";
import { ClipboardList } from "lucide-react";

export default async function ReportsPage() {
  const session = await getSession();
  if (!session?.user) redirect("/login");
  if (!can(session.user.role, "reports:generate")) {
    redirect("/dashboard?error=forbidden");
  }

  const [generations, caseGroups] = await Promise.all([
    prisma.auditLogEntry.findMany({
      where: { action: "REPORT_GENERATED" },
      orderBy: { timestamp: "desc" },
      take: 100,
      include: {
        actor: { select: { name: true, role: true } },
      },
    }),
    prisma.evidenceItem.groupBy({
      by: ["caseNumber"],
      _count: { _all: true },
      orderBy: { caseNumber: "asc" },
    }),
  ]);

  const caseNumbers = caseGroups.map((g) => g.caseNumber);

  return (
    <div>
      <PageHeader
        eyebrow="Reports"
        title="Custody reporting"
        subtitle="Generate printable Chain of Custody PDFs per exhibit or by case, typeset in a formal LaTeX-style layout."
        actions={<ModuleBadge module="reports" />}
      />

      <div className="mb-6">
        <BulkCaseReportForm caseNumbers={caseNumbers} />
      </div>

      <h2 className="mb-3 text-section-title text-canvas-foreground">
        Previously generated reports
      </h2>
      <p className="mb-3 text-muted-ems">
        Logged as append-only <code>REPORT_GENERATED</code> audit entries (no
        separate report table).
      </p>

      {generations.length === 0 ? (
        <EmptyState
          icon={ClipboardList}
          title="No reports generated yet"
          description="Open an evidence item’s Reports tab or use bulk case generate above to create the first PDF."
        />
      ) : (
        <div className="overflow-hidden rounded-lg border border-border bg-card shadow-card">
          <table className="w-full min-w-[720px] text-left text-sm">
            <thead className="border-b border-border bg-secondary/60">
              <tr>
                <th className="px-4 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  Generated
                </th>
                <th className="px-4 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  Kind
                </th>
                <th className="px-4 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  Evidence / case
                </th>
                <th className="px-4 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  Filename
                </th>
                <th className="px-4 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  Generated by
                </th>
              </tr>
            </thead>
            <tbody>
              {generations.map((g) => {
                const meta = g.metadata as Record<string, unknown>;
                const kind =
                  typeof meta.reportKind === "string" ? meta.reportKind : "—";
                const evidenceId =
                  typeof meta.evidenceId === "string" ? meta.evidenceId : null;
                const caseNumber =
                  typeof meta.caseNumber === "string" ? meta.caseNumber : null;
                const filename =
                  typeof meta.filename === "string" ? meta.filename : "—";

                return (
                  <tr
                    key={g.id}
                    className="border-b border-border last:border-0 hover:bg-secondary/40"
                  >
                    <td className="px-4 py-3 whitespace-nowrap text-muted-ems">
                      {format(g.timestamp, "dd MMM yyyy HH:mm")}
                    </td>
                    <td className="px-4 py-3">
                      <span className="rounded-md border border-accent-reports/30 bg-accent-reports/10 px-2 py-0.5 text-xs font-medium text-accent-reports">
                        {kind}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      {evidenceId ? (
                        <Link
                          href={`/evidence/${g.entityId}?tab=reports`}
                          className="font-mono text-sm font-medium text-accent-reports hover:underline"
                        >
                          {evidenceId}
                        </Link>
                      ) : (
                        "—"
                      )}
                      {caseNumber ? (
                        <p className="text-muted-ems">Case {caseNumber}</p>
                      ) : null}
                    </td>
                    <td className="px-4 py-3 font-mono text-xs">{filename}</td>
                    <td className="px-4 py-3">
                      {g.actor.name}
                      <span className="block text-muted-ems">{g.actor.role}</span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
